SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";
CREATE DATABASE IF NOT EXISTS `travelerdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `travelerdb`;

CREATE TABLE `categories` (
  `id` int(11) NOT NULL,
  `title` varchar(150) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `categories` (`id`, `title`) VALUES
(82, 'Manga'),
(83, 'Anime Hay'),
(84, 'Review'),
(85, 'Tin Tức'),
(86, 'BXH'),
(87, 'Light Novel');

CREATE TABLE `members` (
  `id` int(11) NOT NULL,
  `name` varchar(150) NOT NULL,
  `avatar` varchar(150) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `members` (`id`, `name`, `avatar`) VALUES
(1, 'Nguyen Ngoc Lam', '116637328_p0_square1200.jpg'),
(2, 'Nguyen Mai Linh', '117052416_p0_square1200.jpg'),
(3, 'Tran Thi Hong Dao', '117289013_p0_square1200.jpg'),
(4, 'Ho Van Cuong', 'b5ac4a5642d14db3876f4212306c58bc.png~tplv-0es2k971ck-image(2).png'),
(5, 'Anh Long', 'avatar (7).png'),
(6, 'Ngo Minh Phu', 'OIP (2).jpg'),
(7, 'Nguyen Thanh Lam', 'b5ac4a5642d14db3876f4212306c58bc.png~tplv-0es2k971ck-image(3).png');

CREATE TABLE `posts` (
  `id` int(11) NOT NULL,
  `title` varchar(150) NOT NULL,
  `picture` varchar(150) NOT NULL,
  `content` text NOT NULL,
  `categoryid` int(11) NOT NULL,
  `datecreated` date NOT NULL,
  `createdby` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `posts` (`id`, `title`, `picture`, `content`, `categoryid`, `datecreated`, `createdby`) VALUES
(36, 'Kỷ niệm 10 năm ra mắt, tác giả Re: Zero tuyên bố rằng \"câu chuyện này nhất định sẽ có happy ending\"', 'pic2-1650946993680394357604.webp', 'Đó là thông tin mới nhất về light novel Re: Zero khi tác giả đã lên tiếng nói về cái kết được cho là có hậu dành cho dàn nhân vật chính.\r\nĐể kỷ niệm 10 năm light novel Re: Zero thì tác giả của bộ truyện, Tappei Nagatsuki đã tổ chức một buổi phát sóng trên \"Twitter Spaces\", nơi anh đã trả lời rất nhiều câu hỏi của người hâm mộ. Nhiều thông tin mới đã được tiết lộ về bộ truyện trong quá trình sáng tác, nhưng một điều khiến dân mạng xôn xao nhất là liệu bộ truyện có kết thúc có hậu hay không?\r\n\r\nVì chương trình được phát sóng bằng tiếng Nhật nên vẫn chưa có nhiều thông tin cho người hâm mộ trên toàn thế giới. Tuy nhiên, người dùng Twitter, Stride Vollachia (@LoremIpsumVerb) đã tiết lộ một thông tin quan trọng. Đây cũng là người hay có những thông tin khá chính xác về light novel Re: Zero.\r\n\r\nCụ thể Stride Vollachia chia sẻ rằng: \"Khi được hỏi về việc liệu Subaru và Emilia có kết hôn với nhau hay không, tác giả đã nói với người hỏi rằng hãy yên tâm rằng Re: Zero sẽ có một kết thúc có hậu.\" Theo tác giả, các phần quan trọng nhất của Re: Zero là: Arc One và Arc cuối cùng - Arc Eleven.', 82, '2024-05-13', 3),
(37, 'BXH anime mùa xuân 2022 tuần 2', 'dav3-16500799422541177590428.webp', 'Đứng đầu trong tuần thứ 2 với 12.93% số phiếu bầu là Spy x Family. Đúng như sự kỳ vọng của khán giả hâm mộ, Spy x Family tập đầu tiên đã đón nhận rất nhiều sự ủng hộ từ các fan hâm mộ. Trong tập 1, câu chuyện về nhiệm vụ mới của anh chàng Loid và cơ duyên với cô bé Anya được các fan đón nhận nhiệt tình.\r\n\r\nĐầu tiên, phải công nhận rằng anime Spy x Family rất bám sát nguyên tác manga, thậm chí phần tạo hình nhân vật còn xuất sắc hơn rất nhiều. Chàng điệp viên Loid gây ấn tượng bởi bề ngoài đẹp trai và một phong cách ăn mặc chuẩn nam thần trong các bộ anime. Trong khi đó thì cô bé Anya không những giữ được các hoạt cảnh vô cùng dễ thương trong manga mà ở anime, tính cách và hình tượng nhân vật này rất phù hợp để trở thành một cô bé chiếm trọn trái tim của fan hâm mộ.\r\n\r\nĐứng thứ 2 trong danh sách này là một siêu phẩm khác cũng lên sóng trong anime mùa xuân 2022 đó chính là Kaguya-sama: Love Is War -Ultra Romantic. Cuộc Chiến Tỏ Tình là tựa anime chuyển thể từ manga rom-com (tình cảm hài hước) cùng tên do Akasaka Aka sáng tác. Tác phẩm xoay quanh chuyện tình éo le giữa Kaguya Shinomiya và Miyuki Shirogane. Vì bản tính hiếu thắng, cả hai - dù rất thích nhau - nhưng lại không muốn tỏ tình trước và luôn tìm cách để người kia chủ động \"ra tay\" trước.\r\n\r\nGiữ vững phòn độ từ 2 mùa trước thì trong tập đầu của mùa thứ 3 này đã mang đến cho khán giả những cảnh phim vô cùng ấn tượng của cặp đôi nhân vật chính Kaguya Shinomiya và Miyuki Shirogane. Với 8.56% số phiếu bầu, vị trí thứ 2 trên bảng xếp hạng anime mùa xuân 2022 tuần thứ 2 là một kết quả xứng đáng.\r\n\r\n', 86, '2024-05-13', 2),
(38, 'Review anime: My Dress-Up Darling', 'download.jpg', 'My Dress-Up Darling mùa đầu tiên đã kết thúc sau 12 tập phim. Mặc dù được phát sóng cùng với hàng loạt anime nổi tiếng khác trong mùa đông 2022 này tuy nhiên tân binh này vẫn chiếm một thứ hạng cao trên bảng xếp hạng. Trong 2 tập cuối, My Dress-Up Darling đã đánh bại Attack on Titan để chiếm lấy ngôi vị đầu bảng xếp hạng.\r\n\r\nVậy điều gì đã tạo nên thành công của siêu phẩm này, hãy cùng chúng tôi điểm qua nhé!', 84, '2024-05-13', 1),
(39, 'Spice & Wolf chính thức được chuyển thể thành anime', 'pou1-1645781287858719264964.webp', 'Đây đang là thông tin anime hot nhất trong hôm nay, ngày chứng kiến loạt light novel nổi tiếng Spice & Wolf chính thức được chuyển thể thành anime.\r\nMới đây nhất thì Trang web chính thức của tác giả Isuna Hasekura đã bắt đầu phát trực tuyến một video để thông báo rằng một bộ anime mới dựa trên bộ light novel Spice & Wolf của ông sẽ được thực hiện. Thông báo không nói rõ liệu anime là phần tiếp theo hay là bản làm lại nhưng nó có dòng giới thiệu như sau:\"Chúng ta sẽ bắt tay vào một cuộc hành trình lần nữa chứ?\" Thông tin về dự án anime này được công bố vào dịp kỷ niệm 15 năm ngày ra mắt loạt light novel nổi tiếng này.', 87, '2024-05-13', 2),
(40, 'Top 10 anime xuất sắc nhất năm 2021', 'ran3-16439474036511169929934.webp', 'ới đây nhất bảng xếp hạng 10 anime xuất sắc nhất của năm 2021 đã được công bố. Vượt lên tất cả các siêu phẩm khác, Thất Nghiệp Chuyển Sinh xuất sắc cán đích ở vị trí đầu tiên.\r\nNhư chúng tôi đã đưa tin, Anime Corner là đơn vị đã tổ chức cuộc bầu chọn bảng xếp hạng top 10 anime xuất sắc nhất mỗi năm. Mới đây nhất, danh sách 10 anime xuất sắc nhất năm 2021 đã được công bố với hơn 100.000 phiếu bầu ngẫu nhiên đến từ các fan trên toàn thế giới. Và sau đây là kết quả\r\n\r\nĐứng đầu danh sách này chính là Mushoku Tensei - Thất Nghiệp Chuyển Sinh. Có thể nói rằng cả 2 phần của anime này đã mang đến cho các fan hâm mộ những phút giây giải trí tuyệt vời. Rudeus và cô nàng Eris cùng câu chuyện khám phá thế giới của cặp đôi này đã mang đến cho tất cả khán giả một câu chuyện tuyệt vời về tình bạn, tình yêu và những câu chuyện cuộc sống vô cùng ý nghĩa. Mặc dù gặp một số phốt về việc lạm dụng quá nhiều hình ảnh nhạy cảm thế nhưng Mushoku Tensei - Thất Nghiệp Chuyển Sinh vẫn vượt qua nhiều tên tuổi khác giành lấy ngôi vị đầu bảng.\r\n\r\n', 86, '2024-05-13', 3),
(41, 'Bộ đôi anime tình cảm lãng mạn gây tiếng vang trong mùa đông 2022', 'mc2-1642925089469808982455.webp', 'Dù không thể so sánh với những anime hành động như Attack on Titan hay Kimetsu no Yaiba tuy nhiên mùa đông 2022 này đánh dấu sự quay trở lại của những bộ phim tình cảm lãng mạn.\r\nAnime mùa đông 2022 đang trải qua tuần phát sóng thứ 3 với rất nhiều siêu phẩm. Mùa phim này có tổng cộng hơn 40 anime mới và cũ được tiếp tục phát sóng. Tâm điểm của sự chú ý tập trung vào 2 cái tên là Kimetsu no Yaiba: Yuukaku-hen và Attack on Titan: The Final Season Part 2. Những phân cảnh hành động mãn nhãn và dòng phim shonen vẫn luôn là sự lựa chọn số 1 của fan hâm mộ.\r\n\r\nTuy nhiên bên cạnh dòng anime hành động thì một dòng phim khác vốn dĩ đã không quá thành công trong vài năm trở lại đây là thể loại tình cảm, lãng mạn đã có sự quay lại đầy ấn tượng với những dấu ấn đậm nét. Cụ thể sau 2 tuần phát sóng tại anime mùa đông 2022, bộ đôi ở thể loại này là My Dress-Up Darling và Akebi’s Sailor Uniform đang thực sự mang đến cho khán giả những sản phẩm chất lượng ở thể loại anime tình cảm, lãng mạn.', 85, '2024-05-13', 2),
(42, 'Top 10 anime lấy chủ đề về samurai cho anh em mê kiếm sĩ cày dần từ giờ đến tết', 'sy2-16427562379361121700559.webp', 'Cùng chúng tôi điểm qua những anime lấy chủ đề về các samurai nổi tiếng trong văn hóa Nhật Bản mà bạn nên xem một lần nhé!\r\nVăn hóa Nhật Bản nổi tiếng với những samurai mạnh mẽ, kiên cường và tinh thần thượng võ. Chính vì vậy không khó để chúng ta được chứng kiến những anime lấy chủ đề về samurai được nhiều người yêu thích của ngành công nghiệp sản xuất phim hoạt hình của Nhật Bản. Cùng chúng tôi điểm qua 10 anime Nhật Bản nổi tiếng khi nói về các samurai hùng mạnh nhé!\r\n\r\nSamurai Deeper Kyo là một anime hấp dẫn nói về năm 1600, tại chiến trường Sekigahara phủ đầy sương mù, một trận chiến quyết liệt được diễn ra bởi hai vị kiếm sĩ mẫu mực. Một trong số đó là Kyoushirou Mibu, một chiến binh cao thủ và đầy cao quý sở hữu sức mạnh độc đáo của gia tộc Mibu. Người kia là tên đã giết hàng ngàn người, có đôi mắt và mái tóc màu đỏ của máu - Mắt quỷ Kyo.Trận chiến huyền thoại của họ đã bị gián đoạn bởi một thiên thạch từ trên trời rơi xuống chiến trường đó khiến cả hai biến mất.\r\n\r\nCâu chuyện bắt đầu sau 4 năm kể từ trận chiến năm ấy, một thợ săn tiền thưởng có tên là Yuya Shiina đang săn lùng Kyoushirou, là một tên lang băm xảo quyệt, lang thang, nợ nần. Trên đường đi để đòi tiền thưởng của anh ta, họ bị tấn công bởi một con quái vật hung bạo đang tìm cách nuốt chửng Kyoushirou. Cuộc chạm trán này đã đánh thức Mắt Quỷ Kyo, tâm trí đã bị kẹt trong thân xác của Kyo từ cuộc chiến định mệnh năm đó. Từ đó bắt đầu một câu chuyện vĩ đại về hai kiếm khách huyền thoại và những bí mật vô cùng hấp dẫn.', 86, '2024-05-13', 4),
(43, 'Top 5 anime ra mắt vào tháng 1 năm 2022', 'kim4-16388746443261167522318.webp', 'Một mùa anime nữa đang đến rất gần, để mở màn cho một năm 2022 được dự báo là hết sức hấp dẫn, 5 cái tên sau đây sẽ khiến bạn ngây ngất trong tháng 1 năm sau!\r\nDịp đầu năm luôn là nơi để các siêu phẩm anime hấp dẫn ra đời nhằm tạo ra một khởi đầu thuận lợi cho một năm anime tại Nhật Bản. Cùng chúng tôi điểm qua 5 cái tên sẽ phát sóng vào tháng 1 sang năm, những tác phẩm mang theo nhiều hy vọng tới từ nhà sản xuất nhé!\r\n\r\n1. Kimetsu No Yaiba Yuukaku-hen\r\n2. Karakai Jouzu No Takagi-san season 3\r\n3. Sono Bisque Doll Wa Koi Wo Suru\r\n4. Orient\r\n5. Koroshi Ai', 86, '2024-05-13', 1),
(44, 'Review Anime: Sword Art Online', 'images.jpg', 'Dường như không có gì quyến rũ hơn việc được lặn đầu vào thế giới ảo của Sword Art Online - một anime được yêu mến không chỉ ở Nhật Bản mà còn đến khắp thế giới. Khám phá quy định của game, bí ẩn của các nhân vật và thể loại anime nổi tiếng này qua 300 từ ngắn gọn này.\r\n\r\nSword Art Online mở màn với Kirito - một game thủ tinh túy thâm gia vào trò chơi mmo thực tế ảo cùng tên. Tuy nhiên, sự hồi hộp cầu kì của mọi người sớm hóa ra là nỗi khiếp đảm - họ bị kẹt trong trò chơi, và nếu bị chết trong game, họ cũng sẽ chết ngoài thực tế.\r\n\r\nTừ đây, cùng với nhân vật nữ chính Asuna, Kirito dấn thân vào cuộc chiến giành tự do. Câu chuyện càng gây cấn với sự xuất hiện của các boss quái vật mạnh mẽ và phi vụ cứu con tin. Không chỉ vậy, tình yêu giữa Kirito và Asuna cũng ngày càng sâu đậm, khiến các fan hâm mộ hào hứng.\r\n\r\nĐiều làm cho Sword Art Online trở nên đặc biệt chính là môi trường sống động và chi tiết, từ khu rừng nguy hiểm, thánh địa linh thiêng cho đến những thành phố nhộn nhịp. Cười cùng những màn chế giễu gia đình và bạn bè, xúc động với những mối tình đẹp và nghẹt thở trong những trận đánh thực tế ảo, Sword Art Online mang đến cho chúng ta một thế giới đầy tưởng tượng.\r\n\r\nNếu bạn yêu thích thể loại anime hành động và phiêu lưu, thì Sword Art Online không thể bỏ qua. Đây rõ ràng là một trong những series anime hay nhất ra mắt trong những năm gần đây.', 84, '2024-05-13', 2),
(45, 'Review anime: Your Name', 'download (1).jpg', '\"Your Name\" - tên tiếng Anh của \"Kimi no Na wa\" - là một bộ phim hoạt hình Nhật Bản tái ngộ lại lòng đam mê anime của hàng triệu khán giả trên toàn thế giới. Dưới bàn tay tài hoa của đạo diễn Makoto Shinkai, \"Your Name\" là một câu chuyện tình yêu, định mệnh và thời gian qua lăng kính của hai nhân vật chính, Mitsuha và Taki.\r\n\r\nTruyện phim xoay quanh cuộc gặp gỡ tưởng chừng như bất khả thi của cô gái Mitsuha sống ở một thị trấn nhỏ ở vùng núi và anh chàng Taki đang sinh sống tại thành phố lớn Tokyo. Họ bắt đầu trải qua trạng thái hoán đổi thân xác, biến cố này không chỉ mang lại sự bối rối, mà còn mở ra con đường để Mitsuha và Taki hiểu rõ hơn về nhau và mối tình đầy định mệnh của họ.\r\n\r\nThành công của \"Your Name\" không chỉ nằm ở tuyến kịch tính gay cấn của cốt truyện, mà còn ở cách đạo diễn Makoto Shinkai tinh tế vẽ nên nền tảng văn hoá Nhật Bản nền tảng, từ lễ rửa sake, bữa cơm gia đình đến cảnh đẹp như tranh vẽ của thành phố Tokyo và vùng núi Itomori.\r\n\r\nKhông chỉ vậy, phim còn gây ấn tượng bởi nhạc nền du dương và lời hát ý nghĩa của ban nhạc rock Nhật Bản Radwimps. Những giai điệu này khiến trái tim khán giả rung động, và càng làm sâu sắc hơn khía cạnh lãng mạn, cảm xúc của bộ phim.\r\n\r\nNếu bạn đang tìm kiếm một bộ anime có khả năng chạm đến trái tim, khám phá vẻ đẹp của tinh yêu và cuộc sống, \"Your Name\" chính là sự lựa chọn tuyệt vời.', 84, '2024-05-13', 1),
(46, 'Light Novel: Thám tử đã chết đang rất hot', 'download (2).jpg', 'Thám tử đã chết (tên gốc: Tantei wa mou shindeiru) là series light novel trinh thám của tác giả mới Nigozyu, người đã chiến thắng giải thưởng tân binh của MF Bunko J lần thứ 15 dành cho các tác giả Light novel mới triển vọng. Tính tới thời điểm hiện tại, Thám tử đã chết đã ra mắt 6 tập tại Nhật Bản với doanh số ấn tượng 850.000 bản được bán ra cùng hàng loạt các phiên bản chuyển thể truyện tranh và mới nhất là TV series anime cũng đang được công chiếu bản quyền tại Việt Nam, thu hút hàng trăm nghìn lượt xem mỗi tập.\r\n\r\n \r\n\r\nChương mở đầu – chương kết.\r\n\r\n \r\n\r\nVào một ngày nọ, tôi - Kimizuka Kimihiko, người đã từng có một thời gian làm trợ thủ của Thám tử Bậc thầy, bị bắt cóc cùng với Natsunagi, Saikawa và Charlotte. Chúng tôi được xem lại sự thật về cái chết của Siesta một năm trước. Và rồi, một cô gái với ngoại hình giống hệt Siesta xuất hiện trước đám còn đang sửng sốt chẳng thốt nên lời là chúng tôi, nói rằng trong đoạn phim vừa chiếu ẩn giấu một “lỗi sai”.\r\n\r\n \r\n\r\n“Hình như tôi không giỏi trong việc đoán định cảm xúc của người\r\n\r\nkhác.”, đây chính là sơ sót của một Siesta hoàn hảo.\r\n\r\n \r\n\r\nCảm giác yếu ớt vì là thám tử bậc thầy mà không thể tìm ra. Trong lúc tìm kiếm “lỗi sai” đó, chúng tôi cũng đồng thời nhận ra được ý nghĩa thực sự của việc kế thừa danh hiệu Thám tử bậc thầy. Vị thám tử đã chết. Sự thật về cái chết của cô ấy cũng đã được tiết lộ. Nhưng vẫn còn là quá sớm để gióng lên hồi kết.\r\n\r\n ', 87, '2024-05-16', 1),
(47, 'Light Novel: Tiệm Sách Cũ Biblia', 'download (3).jpg', '“Tiệm sách cũ Biblia” là lát cắt vào thế giới của những người cuồng sách giấy, đặc biệt là sách cũ.\r\n\r\nTrong khi sách điện tử đang phát triển mạnh mẽ và phạm vi giải trí hiện đại đã quá mênh mang màu sắc, dễ dàng kéo xa người ta khỏi những trang giấy lặng câm bình dị, thì ở Biblia, vẫn có những người giở đủ mánh khóe âm mưu, thậm chí sẵn sàng phạm tội rồi đi tù vì sách.\r\n\r\nCũng ở Biblia, sách có thể vun đắp một quan hệ, đồng thời làm tan vỡ một quan hệ khác. Sách còn là phương tiện để phát triển trí tuệ, không chỉ qua nội dung nó truyền tải, mà qua cả việc khám phá những bí ẩn xoay quanh chủ nhân hay vòng đời mỗi cuốn sách. Tác dụng kì thú này được hình ảnh hóa ở Shinokawa Shioriko, chủ tiệm sách Biblia.\r\n\r\nSau 7 tập chính truyện dành cho hành trình khám phá bí ẩn cũng như đời tư của Shioriko, 2 tập tiếp theo được dành cho cô con gái Tobirako.\r\n\r\nỞ tập thứ 2 về cô bé, với tiêu đề “Tobirako và thời gian bỏ ngỏ”, độc giả được dẫn vào hành trình truy vết một cuốn sách không hề tồn tại của nhà văn trinh thám Yokomizo Seishi.\r\n\r\nKhông tham gia trực tiếp, chỉ bằng cách đọc các dữ kiện tại chỗ, Tobirako đã đưa ra những suy luận xác đáng đến mức người bà quỷ quyệt của em cũng phải ngạc nhiên, hứa hẹn sẽ là truyền nhân xuất sắc về óc phán đoán ở thế hệ tiếp theo của nhà Shinokawa.\r\n\r\nGiá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, thuế nhập khẩu (đối với đơn hàng giao từ nước ngoài có giá trị trên 1 triệu đồng).....', 87, '2024-05-13', 4);


ALTER TABLE `categories`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `members`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `posts`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `categories`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=94;

ALTER TABLE `members`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=20;

ALTER TABLE `posts`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=58;
